// client/src/pages/RCUView.tsx
import { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Badge } from '@/components/ui/badge';

interface CoolingUnitData {
  machineState: boolean;
  selfCheckState: boolean;
  coolingState: boolean;
  heatingState: boolean;
  dehumidifierState: boolean;
  humidifierState: boolean;
  dryContactAlarmingState: boolean;
  returnAirTemp: number;
  returnAirHumidity: number;
  supplyAirTemp: number;
  supplyAirHumidity: number;
  internalFanRpm: number;
  externalFanRpm: number;
  condenserMotorRpm: number;
  dischargeTemp: number;
  suctionTemp: number;
  evaporatorTemp: number;
  acVoltage: number;
}

export default function RCUView() {
  const [showInternalGridStates, setShowInternalGridStates] = useState(false);
  const [showInternalGridTemps, setShowInternalGridTemps] = useState(false);
  const [showInternalGridMotors, setShowInternalGridMotors] = useState(false);
  const [triggerExpandAll, setTriggerExpandAll] = useState(false);

  const { data: coolingData, isLoading } = useQuery<CoolingUnitData>({
    queryKey: ['/api/cooling-unit/data'],
    refetchInterval: 1000,
  });

  const toggleExpansion = () => {
    if (triggerExpandAll) {
      setShowInternalGridMotors(false);
      setShowInternalGridStates(false);
      setShowInternalGridTemps(false);
    } else {
      setShowInternalGridMotors(true);
      setShowInternalGridStates(true);
      setShowInternalGridTemps(true);
    }
    setTriggerExpandAll(!triggerExpandAll);
  };

  const degreeSymbol = '°F';
  const lastUpdated = new Date().toLocaleString();

  // Convert temperatures from Celsius to Fahrenheit
  const convertTemp = (celsius: number) => ((celsius * 1.8) + 32).toFixed(1);

  if (isLoading) {
    return (
      <main className="container mx-auto px-4 py-8 text-white">
        <div className="flex justify-center items-center h-64">
          <div className="text-xl">Loading cooling unit data...</div>
        </div>
      </main>
    );
  }

  const returnAirTempReal = coolingData ? convertTemp(coolingData.returnAirTemp) : '0.0';
  const returnAirHumReal = coolingData ? coolingData.returnAirHumidity.toFixed(0) : '0';
  const supplyAirTempReal = coolingData ? convertTemp(coolingData.supplyAirTemp) : '0.0';
  const supplyAirHumReal = coolingData ? (coolingData.supplyAirHumidity < 1000 ? coolingData.supplyAirHumidity.toFixed(0) : '-') : '0';
  const internalFanReal = coolingData ? coolingData.internalFanRpm.toString() : '0';
  const externalFanReal = coolingData ? coolingData.externalFanRpm.toString() : '0';
  const condenserMotorReal = coolingData ? coolingData.condenserMotorRpm.toString() : '0';
  const dischargeTempReal = coolingData ? (coolingData.dischargeTemp < 500 ? convertTemp(coolingData.dischargeTemp) : '-') : '0.0';
  const suctionTempReal = coolingData ? convertTemp(coolingData.suctionTemp) : '0.0';
  const evapTempReal = coolingData ? convertTemp(coolingData.evaporatorTemp) : '0.0';
  const acVoltageReal = coolingData ? coolingData.acVoltage.toFixed(1) : '0.0';

  const machineActiveReal = coolingData?.machineState || false;
  const selfCheckActiveReal = coolingData?.selfCheckState || false;
  const coolingActiveReal = coolingData?.coolingState || false;
  const heatingActiveReal = coolingData?.heatingState || false;
  const dehumidifierActiveReal = coolingData?.dehumidifierState || false;
  const humidifierActiveReal = coolingData?.humidifierState || false;
  const dryContactAlarmingActiveReal = coolingData?.dryContactAlarmingState || false;

  return (
    <main className="container mx-auto px-4 py-8 text-white">
      {/* Header and Expansion/Collapse Control */}
      <div className="flex flex-row">
        <div className="flex flex-1 justify-start">
          <h1 className="mt-6">Cooling Unit Readings:</h1>
        </div>
        <div className="flex justify-end mt-6">
          <button onClick={toggleExpansion}>
            <div>{triggerExpandAll ? '[ Collapse All ]' : '[ Expand All ]'}</div>
          </button>
        </div>
      </div>
      
      {/* Last updated section */}
      <div className="flex justify-center uppercase text-xs italic mt-2">
        Last updated: <div>&nbsp; {lastUpdated}</div>
      </div>

      {/* States Grid */}
      <div className="max-h-fit my-6 grid grid-rows-1 border rounded-3xl bg-slate-800">
        <div className="my-6 mx-2">
          <div className="container flex flex-row">
            <div className="flex items-start">States:</div>
            <div className="flex gap-3 flex-1 justify-end">
              <button onClick={() => setShowInternalGridStates(!showInternalGridStates)}>
                <div>{showInternalGridStates ? '[ - ]' : '[ + ]'}</div>
              </button>
            </div>
          </div>
          
          {showInternalGridStates && (
            <div className="transition-all duration-500 ease-in-out grid grid-cols-2 m-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-7 mx-auto p-2 gap-8 text-white w-full">
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${machineActiveReal ? 'dark:bg-green-600' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Machine:</div>
                <div className="flex justify-center">
                  <Badge className={machineActiveReal ? 'status-badge-on' : 'status-badge-off'}>
                    {machineActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
              
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${selfCheckActiveReal ? 'dark:bg-blue-500' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Self-Check:</div>
                <div className="flex justify-center">
                  <Badge className={selfCheckActiveReal ? 'status-badge-blue' : 'status-badge-off'}>
                    {selfCheckActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
              
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${coolingActiveReal ? 'dark:bg-blue-500' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Cooling:</div>
                <div className="flex justify-center">
                  <Badge className={coolingActiveReal ? 'status-badge-on' : 'status-badge-off'}>
                    {coolingActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
              
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${heatingActiveReal ? 'dark:bg-red-500' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Heating:</div>
                <div className="flex justify-center">
                  <Badge className={heatingActiveReal ? 'status-badge-on' : 'status-badge-off'}>
                    {heatingActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
              
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${dehumidifierActiveReal ? 'dark:bg-purple-500' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Dehumidifier:</div>
                <div className="flex justify-center">
                  <Badge className={dehumidifierActiveReal ? 'status-badge-purple' : 'status-badge-off'}>
                    {dehumidifierActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
              
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${humidifierActiveReal ? 'dark:bg-purple-500' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Humidifier:</div>
                <div className="flex justify-center">
                  <Badge className={humidifierActiveReal ? 'status-badge-purple' : 'status-badge-off'}>
                    {humidifierActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
              
              <div className={`custom-grid border-none dark:rounded-full dark:bg-gray-600 ${dryContactAlarmingActiveReal ? 'dark:bg-purple-500' : ''}`}>
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Dry Contact Alarming:</div>
                <div className="flex justify-center">
                  <Badge className={dryContactAlarmingActiveReal ? 'status-badge-purple' : 'status-badge-off'}>
                    {dryContactAlarmingActiveReal ? 'ON' : 'OFF'}
                  </Badge>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Temperature Grid */}
      <div className="max-h-fit my-6 grid grid-rows-1 border rounded-3xl bg-slate-800">
        <div className="my-6 mx-2">
          <div className="container flex flex-row">
            <div className="flex items-start">Temperatures / Humidity:</div>
            <div className="flex gap-3 flex-1 justify-end">
              <button onClick={() => setShowInternalGridTemps(!showInternalGridTemps)}>
                <div>{showInternalGridTemps ? '[ - ]' : '[ + ]'}</div>
              </button>
            </div>
          </div>
          
          {showInternalGridTemps && (
            <div className="transition-all duration-500 ease-in-out grid grid-cols-2 m-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 mx-auto p-2 gap-8 text-white w-full">
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Return Air<br />Temp ({degreeSymbol}):
                </div>
                <div className="text-4xl">{returnAirTempReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Supply Air<br />Temp ({degreeSymbol}):
                </div>
                <div className="text-4xl">{supplyAirTempReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Discharge<br />Temp ({degreeSymbol}):
                </div>
                <div className="text-4xl">{dischargeTempReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Suction<br />Temp ({degreeSymbol}):
                </div>
                <div className="text-4xl">{suctionTempReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Evaporator<br />Temp ({degreeSymbol}):
                </div>
                <div className="text-4xl">{evapTempReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Return Air<br />Humidity:
                </div>
                <div className="text-4xl">{returnAirHumReal}%</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Supply Air<br />Humidity:
                </div>
                <div className="text-4xl">{supplyAirHumReal}%</div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Motors Grid */}
      <div className="max-h-fit my-6 grid grid-rows-1 border rounded-3xl bg-slate-800">
        <div className="my-6 mx-2">
          <div className="container flex flex-row">
            <div className="flex items-start">Motors / Electrical:</div>
            <div className="flex gap-3 flex-1 justify-end">
              <button onClick={() => setShowInternalGridMotors(!showInternalGridMotors)}>
                <div>{showInternalGridMotors ? '[ - ]' : '[ + ]'}</div>
              </button>
            </div>
          </div>
          
          {showInternalGridMotors && (
            <div className="transition-all duration-500 ease-in-out grid grid-cols-2 m-2 sm:grid-cols-3 md:grid-cols-4 mx-auto p-2 gap-8 text-white w-full">
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Internal Fan<br />(RPM):
                </div>
                <div className="text-4xl">{internalFanReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  External Fan<br />(RPM):
                </div>
                <div className="text-4xl">{externalFanReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  Condenser Motor<br />(RPM):
                </div>
                <div className="text-4xl">{condenserMotorReal}</div>
              </div>
              
              <div className="custom-grid">
                <div className="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">
                  AC Voltage<br />(V):
                </div>
                <div className="text-4xl">{acVoltageReal}</div>
              </div>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}

// vue-client/src/views/RCUView.vue
<template>
  <main class="container mx-auto px-4 py-8 text-white">
    <!-- Header and Expansion/Collapse Control -->
    <div class="flex flex-row">
      <div class="flex flex-1 justify-start">
        <h1 class="mt-6">Cooling Unit Readings:</h1>
      </div>
      <div class="flex justify-end mt-6">
        <button @click="toggleExpansion">
          <div v-if="triggerExpandAll">[ Collapse All ]</div>
          <div v-else>[ Expand All ]</div>
        </button>
      </div>
    </div>
    
    <!-- Last updated section -->
    <div class="flex justify-center uppercase text-xs italic mt-2">
      Last updated: <div id="updatedTime">&nbsp; {{ lastUpdated }}</div>
    </div>   

    <!-- States Grid -->
    <div class="max-h-fit my-6 grid grid-rows-1 border rounded-3xl bg-slate-800">
      <div class="my-6 mx-2">
        <div class="container flex flex-row">
          <div class="flex items-start">States:</div>
          <div class="flex gap-3 flex-1 justify-end">
            <button @click="showInternalGridStates = !showInternalGridStates">
              <div v-if="showInternalGridStates">[ - ]</div>
              <div v-else>[ + ]</div>
            </button>
          </div>
        </div>
        <Transition>    
          <div v-show="showInternalGridStates" class="grid grid-cols-2 m-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-7 mx-auto p-2 gap-8 text-white w-full">
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-green-600': machineActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Machine:</div>
              <div class="flex justify-center">
                <div v-if="machineActiveReal">
                  <fwb-badge type="green" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>                        
            </div>
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-blue-500': selfCheckActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Self-Check:</div>
              <div class="flex justify-center">
                <div v-if="selfCheckActiveReal">
                  <fwb-badge type="blue" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>
            </div>
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-blue-500': coolingActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Cooling:</div>
              <div class="flex justify-center">
                <div v-if="coolingActiveReal">
                  <fwb-badge type="green" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>
            </div>
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-red-500': heatingActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Heating:</div>
              <div class="flex justify-center">
                <div v-if="heatingActiveReal">
                  <fwb-badge type="green" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>
            </div>
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-purple-500': dehumidifierActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Dehumidifier:</div>
              <div class="flex justify-center">
                <div v-if="dehumidifierActiveReal">
                  <fwb-badge type="purple" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>
            </div>
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-purple-500': humidifierActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Humidifier:</div>
              <div class="flex justify-center">
                <div v-if="humidifierActiveReal">
                  <fwb-badge type="purple" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>
            </div>
            <div class="custom-grid border-none dark:rounded-full dark:bg-gray-600" :class="{ 'dark:bg-purple-500': dryContactAlarmingActiveReal }">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Dry Contact Alarming:</div>
              <div class="flex justify-center">
                <div v-if="dryContactAlarmingActiveReal">
                  <fwb-badge type="purple" size="md">ON</fwb-badge>
                </div>
                <div v-else>
                  <fwb-badge type="default" size="md">OFF</fwb-badge>
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>
    </div>

    <!-- Temperature Grid -->
    <div class="max-h-fit my-6 grid grid-rows-1 border rounded-3xl bg-slate-800">
      <div class="my-6 mx-2">
        <div class="container flex flex-row">
          <div class="flex items-start">Temperatures / Humidity:</div>
          <div class="flex gap-3 flex-1 justify-end">
            <button @click="showInternalGridTemps = !showInternalGridTemps">
              <div v-if="showInternalGridTemps">[ - ]</div>
              <div v-else>[ + ]</div>
            </button>
          </div>
        </div>
        <Transition>    
          <div v-show="showInternalGridTemps" class="grid grid-cols-2 m-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 mx-auto p-2 gap-8 text-white w-full">
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Return Air<br />Temp ({{ degreeSymbol }}):</div>
              <div class="text-4xl">{{ returnAirTempReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Supply Air<br />Temp ({{ degreeSymbol }}):</div>
              <div class="text-4xl">{{ supplyAirTempReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Discharge<br />Temp ({{ degreeSymbol }}):</div>
              <div class="text-4xl">{{ dischargeTempReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Suction<br />Temp ({{ degreeSymbol }}):</div>
              <div class="text-4xl">{{ suctionTempReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Evaporator<br />Temp ({{ degreeSymbol }}):</div>
              <div class="text-4xl">{{ evapTempReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Return Air<br />Humidity:</div>
              <div class="text-4xl">{{ returnAirHumReal }}%</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Supply Air<br />Humidity:</div>
              <div class="text-4xl">{{ supplyAirHumReal }}%</div>
            </div>
          </div>
        </Transition>
      </div>
    </div>

    <!-- Motors Grid -->
    <div class="max-h-fit my-6 grid grid-rows-1 border rounded-3xl bg-slate-800">
      <div class="my-6 mx-2">
        <div class="container flex flex-row">
          <div class="flex items-start">Motors / Electrical:</div>
          <div class="flex gap-3 flex-1 justify-end">
            <button @click="showInternalGridMotors = !showInternalGridMotors">
              <div v-if="showInternalGridMotors">[ - ]</div>
              <div v-else>[ + ]</div>
            </button>
          </div>
        </div>
        <Transition>    
          <div v-show="showInternalGridMotors" class="grid grid-cols-2 m-2 sm:grid-cols-3 md:grid-cols-4 mx-auto p-2 gap-8 text-white w-full">
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Internal Fan<br />(RPM):</div>
              <div class="text-4xl">{{ internalFanReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">External Fan<br />(RPM):</div>
              <div class="text-4xl">{{ externalFanReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">Condenser Motor<br />(RPM):</div>
              <div class="text-4xl">{{ condenserMotorReal }}</div>
            </div>
            <div class="custom-grid">
              <div class="m-auto grid grid-rows-1 gap-4 text-center text-sm table-label">AC Voltage<br />(V):</div>
              <div class="text-4xl">{{ acVoltageReal }}</div>
            </div>
          </div>
        </Transition>
      </div>
    </div>
  </main>
</template>

<script setup lang="ts">
import { FwbBadge } from 'flowbite-vue'
import { ref, onMounted, computed } from 'vue'
import axios from 'axios'

const showInternalGridStates = ref(false)
const showInternalGridTemps = ref(false)
const showInternalGridMotors = ref(false)
const triggerExpandAll = ref(false)

const toggleExpansion = () => {
  if (triggerExpandAll.value) {
    showInternalGridMotors.value = false
    showInternalGridStates.value = false
    showInternalGridTemps.value = false
  } else {
    showInternalGridMotors.value = true
    showInternalGridStates.value = true
    showInternalGridTemps.value = true
  }
  triggerExpandAll.value = !triggerExpandAll.value
}

const degreeSymbol = ref('°F')

// States
const machineActiveReal = ref(false)
const selfCheckActiveReal = ref(false)
const coolingActiveReal = ref(false)
const heatingActiveReal = ref(false)
const dehumidifierActiveReal = ref(false)
const humidifierActiveReal = ref(false)
const dryContactAlarmingActiveReal = ref(false)

// Variables for real time view
const returnAirTempReal = ref('0.0')
const returnAirHumReal = ref('0')
const supplyAirTempReal = ref('0.0')
const supplyAirHumReal = ref('0')
const internalFanReal = ref('0')
const externalFanReal = ref('0')
const condenserMotorReal = ref('0')
const dischargeTempReal = ref('0.0')
const suctionTempReal = ref('0.0')
const evapTempReal = ref('0.0')
const acVoltageReal = ref('0.0')

const lastUpdated = computed(() => {
  return new Date().toLocaleString()
})

const fetchData = async () => {
  try {
    const response = await axios.get('/api/cooling-unit/data')
    if (response.status === 200) {
      const data = response.data
      
      // Convert temperatures from Celsius to Fahrenheit
      returnAirTempReal.value = ((data.returnAirTemp * 1.8) + 32).toFixed(1)
      returnAirHumReal.value = data.returnAirHumidity.toFixed(0)
      supplyAirTempReal.value = ((data.supplyAirTemp * 1.8) + 32).toFixed(1)
      supplyAirHumReal.value = data.supplyAirHumidity < 1000 ? data.supplyAirHumidity.toFixed(0) : '-'
      internalFanReal.value = data.internalFanRpm.toString()
      externalFanReal.value = data.externalFanRpm.toString()
      condenserMotorReal.value = data.condenserMotorRpm.toString()
      
      machineActiveReal.value = data.machineState
      dischargeTempReal.value = data.dischargeTemp < 500 ? ((data.dischargeTemp * 1.8) + 32).toFixed(1) : '-'
      suctionTempReal.value = ((data.suctionTemp * 1.8) + 32).toFixed(1)
      evapTempReal.value = ((data.evaporatorTemp * 1.8) + 32).toFixed(1)
      acVoltageReal.value = data.acVoltage.toFixed(1)

      selfCheckActiveReal.value = data.selfCheckState || false
      coolingActiveReal.value = data.coolingState
      heatingActiveReal.value = data.heatingState
      dehumidifierActiveReal.value = data.dehumidifierState
      humidifierActiveReal.value = data.humidifierState
      dryContactAlarmingActiveReal.value = data.dryContactAlarmingState
    } else {
      console.error('Error fetching data:', response.status)
    }
  } catch (error) {
    console.error('Error fetching data:', error)
  }
}

onMounted(() => {
  fetchData()
  setInterval(fetchData, 1000) // Fetch data every second
})
</script>
